pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2  -v /var/lib/jenkins/docker:/tmp' 
        }
    }
    options {
        skipStagesAfterUnstable()
    }    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh 'cp target/*.jar /tmp'
            }
        }
        stage('d') {
            agent any
            steps {
                sshagent (credentials: ['git-hub-ssh-key']) {
                    sh 'eval "$(ssh-agent)"'
                    sh 'ssh ubuntu@63.35.222.237 echo hello'
                }    
            }
        }
    }
}
