pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2 -v /root/docker:/opt' 
        }
    }
    options {
        skipStagesAfterUnstable()
    }    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh 'NAME=`mvn help:evaluate -Dexpression=project.name | grep "^[^\[]"`'
                sh 'VERSION=`mvn help:evaluate -Dexpression=project.version | grep "^[^\[]"`'
                sh 'cp ${NAME}-${VERSION}.jar /opt'
            }
        }
        stage('d') {
            steps {
                sshagent (credentials: ['git-hub-ssh-key']) {
                    sh 'ssh ubuntu@63.35.222.237 mkdir 1213'
                }    
            }
        }
    }
}
